require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Panel::PlanfeaturesController do

  # This should return the minimal set of attributes required to create a valid
  # Panel::Planfeature. As you add validations to Panel::Planfeature, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Panel::PlanfeaturesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all panel_planfeatures as @panel_planfeatures" do
      planfeature = Panel::Planfeature.create! valid_attributes
      get :index, {}, valid_session
      assigns(:panel_planfeatures).should eq([planfeature])
    end
  end

  describe "GET show" do
    it "assigns the requested planfeature as @planfeature" do
      planfeature = Panel::Planfeature.create! valid_attributes
      get :show, {:id => planfeature.to_param}, valid_session
      assigns(:planfeature).should eq(planfeature)
    end
  end

  describe "GET new" do
    it "assigns a new planfeature as @planfeature" do
      get :new, {}, valid_session
      assigns(:planfeature).should be_a_new(Panel::Planfeature)
    end
  end

  describe "GET edit" do
    it "assigns the requested planfeature as @planfeature" do
      planfeature = Panel::Planfeature.create! valid_attributes
      get :edit, {:id => planfeature.to_param}, valid_session
      assigns(:planfeature).should eq(planfeature)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Panel::Planfeature" do
        expect {
          post :create, {:planfeature => valid_attributes}, valid_session
        }.to change(Panel::Planfeature, :count).by(1)
      end

      it "assigns a newly created planfeature as @planfeature" do
        post :create, {:planfeature => valid_attributes}, valid_session
        assigns(:planfeature).should be_a(Panel::Planfeature)
        assigns(:planfeature).should be_persisted
      end

      it "redirects to the created planfeature" do
        post :create, {:planfeature => valid_attributes}, valid_session
        response.should redirect_to(Panel::Planfeature.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved planfeature as @planfeature" do
        # Trigger the behavior that occurs when invalid params are submitted
        Panel::Planfeature.any_instance.stub(:save).and_return(false)
        post :create, {:planfeature => {}}, valid_session
        assigns(:planfeature).should be_a_new(Panel::Planfeature)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Panel::Planfeature.any_instance.stub(:save).and_return(false)
        post :create, {:planfeature => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested planfeature" do
        planfeature = Panel::Planfeature.create! valid_attributes
        # Assuming there are no other panel_planfeatures in the database, this
        # specifies that the Panel::Planfeature created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Panel::Planfeature.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => planfeature.to_param, :planfeature => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested planfeature as @planfeature" do
        planfeature = Panel::Planfeature.create! valid_attributes
        put :update, {:id => planfeature.to_param, :planfeature => valid_attributes}, valid_session
        assigns(:planfeature).should eq(planfeature)
      end

      it "redirects to the planfeature" do
        planfeature = Panel::Planfeature.create! valid_attributes
        put :update, {:id => planfeature.to_param, :planfeature => valid_attributes}, valid_session
        response.should redirect_to(planfeature)
      end
    end

    describe "with invalid params" do
      it "assigns the planfeature as @planfeature" do
        planfeature = Panel::Planfeature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Panel::Planfeature.any_instance.stub(:save).and_return(false)
        put :update, {:id => planfeature.to_param, :planfeature => {}}, valid_session
        assigns(:planfeature).should eq(planfeature)
      end

      it "re-renders the 'edit' template" do
        planfeature = Panel::Planfeature.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Panel::Planfeature.any_instance.stub(:save).and_return(false)
        put :update, {:id => planfeature.to_param, :planfeature => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested planfeature" do
      planfeature = Panel::Planfeature.create! valid_attributes
      expect {
        delete :destroy, {:id => planfeature.to_param}, valid_session
      }.to change(Panel::Planfeature, :count).by(-1)
    end

    it "redirects to the panel_planfeatures list" do
      planfeature = Panel::Planfeature.create! valid_attributes
      delete :destroy, {:id => planfeature.to_param}, valid_session
      response.should redirect_to(panel_planfeatures_url)
    end
  end

end
